export const FETCH_ARTICLE_LIST_PENDING = 'App/FETCH_ARTICLE_LIST_PENDING';
export const FETCH_ARTICLE_LIST_SUCCESS = 'App/FETCH_ARTICLE_LIST_SUCCESS';
export const FETCH_ARTICLE_LIST_ERROR = 'App/FETCH_ARTICLE_LIST_ERROR';

export const CREATE_POST_PENDING = 'App/CREATE_POST_PENDING';
export const CREATE_POST_SUCCESS = 'App/CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'App/CREATE_POST_ERROR';
