export const FETCH_ARTICLE_LIST_PENDING = 'App/FETCH_ARTICLE_LIST_PENDING';
export const FETCH_ARTICLE_LIST_SUCCESS = 'App/FETCH_ARTICLE_LIST_SUCCESS';
export const FETCH_ARTICLE_LIST_ERROR = 'App/FETCH_ARTICLE_LIST_ERROR';
