
export const GET_COMMENT_LIST_PENDING = 'App/FETCH_COMMENT_PENDING'
export const GET_COMMENT_LIST_SUCCESS = 'App/FETCH_COMMENT_SUCCESS'
export const GET_COMMENT_LIST_ERROR = 'App/FETCH_COMMENT_ERROR'

export const POST_COMMENT_PENDING = 'App/POST_COMMENT_PENDING'
export const POST_COMMENT_SUCCESS = 'App/POST_COMMENT_SUCCESS'
export const POST_COMMENT_ERROR = 'App/POST_COMMENT_ERROR'
