export const INITIAL_LOAD_NOTIFICATIONS_PENDING = 'FEED/INITIAL_LOAD_NOTIFICATIONS_PENDING'
export const INITIAL_LOAD_NOTIFICATIONS_SUCCESS = 'FEED/INITIAL_LOAD_NOTIFICATIONS_SUCCESS'
export const INITIAL_LOAD_NOTIFICATIONS_ERROR = 'FEED/INITIAL_LOAD_NOTIFICATIONS_ERROR'


export const LOAD_NEXT_NOTIFICATIONS_PENDING = 'FEED/LOAD_NEXT_NOTIFICATIONS_PENDING'
export const LOAD_NEXT_NOTIFICATIONS_SUCCESS = 'FEED/LOAD_NEXT_NOTIFICATIONS_SUCCESS'
export const LOAD_NEXT_NOTIFICATIONS_ERROR = 'FEED/LOAD_NEXT_NOTIFICATIONS_ERROR'

export const CLEAR_UNREAD_NOTIFICATION = 'FEED/CLEAR_UNREAD_NOTIFICATION'
