export const GET_USER_FOLLOWERS_PENDING = `APP/GET_USER_FOLLOWERS_PENDING`
export const GET_USER_FOLLOWERS_SUCCESS = `APP/GET_USER_FOLLOWERS_SUCCESS`
export const GET_USER_FOLLOWERS_ERROR = `APP/GET_USER_FOLLOWERS_ERROR`

export const GET_NEXT_USER_FOLLOWERS_PENDING = `APP/GET_NEXT_USER_FOLLOWERS_PENDING`
export const GET_NEXT_USER_FOLLOWERS_SUCCESS = `APP/GET_NEXT_USER_FOLLOWERS_SUCCESS`
export const GET_NEXT_USER_FOLLOWERS_ERROR = `APP/GET_NEXT_USER_FOLLOWERS_ERROR`


export const GET_USER_FOLLOWINGS_PENDING = `APP/GET_USER_FOLLOWINGS_PENDING`
export const GET_USER_FOLLOWINGS_SUCCESS = `APP/GET_USER_FOLLOWINGS_SUCCESS`
export const GET_USER_FOLLOWINGS_ERROR = `APP/GET_USER_FOLLOWERING_RROR`


export const GET_NEXT_USER_FOLLOWINGS_PENDING = `APP/GET_NEXT_USER_FOLLOWINGS_PENDING`
export const GET_NEXT_USER_FOLLOWINGS_SUCCESS = `APP/GET_NEXT_USER_FOLLOWINGS_SUCCESS`
export const GET_NEXT_USER_FOLLOWINGS_ERROR = `APP/GET_NEXT_USER_FOLLOWINGS_RROR`


export const ADD_FOLLOWER_FOR_USER = `APP/ADD_FOLLOWER_FOR_USER`
export const ADD_FOLLOWING_FOR_USER = `APP/ADD_FOLLOWING_FOR_USER`

export const REMOVE_FOLLOWER_FOR_USER = `APP/REMOVE_FOLLOWER_FOR_USER`
export const REMOVE_FOLLOWING_FOR_USER = `APP/REMOVE_FOLLOWING_FOR_USER`