export const GET_USER_FOLLOWERS_PENDING = `APP/GET_USER_FOLLOWERS_PENDING`
export const GET_USER_FOLLOWERS_SUCCESS = `APP/GET_USER_FOLLOWERS_SUCCESS`
export const GET_USER_FOLLOWERS_ERROR = `APP/GET_USER_FOLLOWERS_ERROR`

export const GET_NEXT_USER_FOLLOWERS_PENDING = `APP/GET_NEXT_USER_FOLLOWERS_PENDING`
export const GET_NEXT_USER_FOLLOWERS_SUCCESS = `APP/GET_NEXT_USER_FOLLOWERS_SUCCESS`
export const GET_NEXT_USER_FOLLOWERS_ERROR = `APP/GET_NEXT_USER_FOLLOWERS_ERROR`


export const GET_USER_FOLLOWINGS_PENDING = `APP/GET_USER_FOLLOWINGS_PENDING`
export const GET_USER_FOLLOWINGS_SUCCESS = `APP/GET_USER_FOLLOWINGS_SUCCESS`
export const GET_USER_FOLLOWINGS_ERROR = `APP/GET_USER_FOLLOWERING_RROR`


export const GET_NEXT_USER_FOLLOWINGS_PENDING = `APP/GET_NEXT_USER_FOLLOWINGS_PENDING`
export const GET_NEXT_USER_FOLLOWINGS_SUCCESS = `APP/GET_NEXT_USER_FOLLOWINGS_SUCCESS`
export const GET_NEXT_USER_FOLLOWINGS_ERROR = `APP/GET_NEXT_USER_FOLLOWINGS_RROR`
