
export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const SIGNUP_USER_PENDING = 'APP/SIGNUP_USER_PENDING'
export const SIGNUP_USER_SUCCESS = 'APP/SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR = 'APP/SIGNUP_USER_ERROR'
