
export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const SIGNUP_USER_PENDING = 'APP/SIGNUP_USER_PENDING'
export const SIGNUP_USER_SUCCESS = 'APP/SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR = 'APP/SIGNUP_USER_ERROR'

export const SET_USER_PASSWORD_PENDING = 'APP/SET_USER_PASSWORD_PENDING'
export const SET_USER_PASSWORD_SUCCESS = 'APP/SET_USER_PASSWORD_SUCCESS'
export const SET_USER_PASSWORD_ERROR = 'APP/SET_USER_PASSWORD_ERROR'


export const UPDATE_USER_PENDING = 'APP/UPDATE_USER_PENDING'
export const UPDATE_USER_SUCCESS = 'APP/UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'APP/UPDATE_USER_ERROR'
