export const GET_USER_POSTS_PENDING = 'App/GET_USER_POSTS_PENDING';
export const GET_USER_POSTS_SUCCESS = 'App/GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_ERROR = 'App/GET_USER_POSTS_ERROR';


export const GET_POST_BY_ID_PENDING = 'App/GET_POST_BY_ID_PENDING';
export const GET_POST_BY_ID_SUCCESS = 'App/GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_ERROR = 'App/GET_POST_BY_ID_ERROR';


export const UPDATE_POST_PENDING = 'App/UPDATE_POST_PENDING';
export const UPDATE_POST_SUCCESS = 'App/UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'App/UPDATE_POST_ERROR';


export const CREATE_POST_PENDING = 'App/CREATE_POST_PENDING';
export const CREATE_POST_SUCCESS = 'App/CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'App/CREATE_POST_ERROR';

export const EDIT_POST = 'App/EDIT_POST'