export const GET_USER_POSTS_PENDING = 'App/GET_USER_POSTS_PENDING';
export const GET_USER_POSTS_SUCCESS = 'App/GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_ERROR = 'App/GET_USER_POSTS_ERROR';


export const GET_POST_BY_ID_PENDING = 'App/GET_POST_BY_ID_PENDING';
export const GET_POST_BY_ID_SUCCESS = 'App/GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_ERROR = 'App/GET_POST_BY_ID_ERROR';
