export const GET_USER_POSTS_PENDING = 'App/GET_USER_POSTS_PENDING';
export const GET_USER_POSTS_SUCCESS = 'App/GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_ERROR = 'App/GET_USER_POSTS_ERROR';
