
export const GET_PROFILE_PENDING = 'App/GET_PROFILE_PENDING'
export const GET_PROFILE_SUCCESS = 'App/GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'App/FETCH_PROFILE_ERROR'

export const FOLLOW_USER_PENDING = 'App/FOLLOW_USER_PENDING'
export const FOLLOW_USER_SUCCESS = 'App/FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_ERROR = 'App/FOLLOW_USER_ERROR'

export const UNFOLLOW_USER_PENDING = 'App/UNFOLLOW_USER_PENDING'
export const UNFOLLOW_USER_SUCCESS = 'App/UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_ERROR = 'App/UNFOLLOW_USER_ERROR'


export const CREATE_USER_INFO = 'APP/CREATE_USER_INFO'
