export const TOAST_MESSAGE = 'TOAST/MESSAGE'
export const TOAST_ERROR = 'TOAST/ERROR'

export const TOAST_REMOVE_FIRST_MESSAGE = 'TOAST/REMOVE_FIRST_MESSAGE'
export const TOAST_REMOVE_FIRST_ERROR = 'TOAST/REMOVE_FIRST_ERROR'